using System;
using System.Collections.Generic;
using System.Globalization;

namespace PiHoleTray;

static class Loc
{
    public static readonly Dictionary<string, string> Langs = new()
    {
        ["en"] = "English",
        ["de"] = "Deutsch",
        ["es"] = "Español",
        ["fr"] = "Français",
        ["it"] = "Italiano",
    };

    private static readonly Dictionary<string, Dictionary<string, string>> All = new()
    {
        ["en"] = new()
        {
            ["title"]           = "Pi-Hole Tray  \u2014  Settings",
            ["connection"]      = "Connection",
            ["url"]             = "URL",
            ["url_hint"]        = "e.g. http://192.168.1.2",
            ["password"]        = "Password / API Key",
            ["pw_hint"]         = "v6: Admin password  \u2022  v5: API Token",
            ["version"]         = "Pi-Hole Version",
            ["v6_label"]        = "v6 (current)",
            ["v5_label"]        = "v5 (legacy)",
            ["options"]         = "Options",
            ["poll_interval"]   = "Poll interval",
            ["seconds"]         = "seconds",
            ["autostart"]       = "  Start with Windows",
            ["language"]        = "Language",
            ["status"]          = "Status",
            ["ready"]           = "Ready",
            ["test_connection"] = "Test connection",
            ["save"]            = "Save",
            ["cancel"]          = "Cancel",
            ["enter_url"]       = "\u26a0  Please enter URL",
            ["testing"]         = "\u23f3  Testing\u2026",
            ["tray_active"]     = "Blocking active",
            ["tray_disabled"]   = "Blocking disabled",
            ["tray_noconn"]     = "No connection",
            ["tray_connecting"] = "Connecting\u2026",
            ["menu_enable"]     = "Enable blocking",
            ["menu_disable"]    = "Disable blocking",
            ["menu_timed"]      = "Disable temporarily",
            ["menu_5min"]       = "5 minutes",
            ["menu_10min"]      = "10 minutes",
            ["menu_30min"]      = "30 minutes",
            ["menu_1h"]         = "1 hour",
            ["menu_2h"]         = "2 hours",
            ["menu_5h"]         = "5 hours",
            ["menu_dashboard"]  = "Open dashboard",
            ["menu_settings"]   = "Settings\u2026",
            ["menu_quit"]       = "Quit",
            ["connected"]       = "Connected",
            ["connected_auth"]  = "Connected & authenticated!",
            ["no_connection"]   = "No connection to:",
            ["timeout"]         = "Timeout",
            ["auth_required"]   = "Authentication required.\nPlease enter password.",
            ["login_failed"]    = "Login failed.\nCheck password.",
            ["conn_failed"]     = "Connection failed.",
        },
        ["de"] = new()
        {
            ["title"]           = "Pi-Hole Tray  \u2014  Einstellungen",
            ["connection"]      = "Verbindung",
            ["url"]             = "URL",
            ["url_hint"]        = "z.B. http://192.168.1.2",
            ["password"]        = "Passwort / API-Key",
            ["pw_hint"]         = "v6: Admin-Passwort  \u2022  v5: API Token",
            ["version"]         = "Pi-Hole Version",
            ["v6_label"]        = "v6 (aktuell)",
            ["v5_label"]        = "v5 (legacy)",
            ["options"]         = "Optionen",
            ["poll_interval"]   = "Abfrage-Intervall",
            ["seconds"]         = "Sekunden",
            ["autostart"]       = "  Mit Windows starten",
            ["language"]        = "Sprache",
            ["status"]          = "Status",
            ["ready"]           = "Bereit",
            ["test_connection"] = "Verbindung testen",
            ["save"]            = "Speichern",
            ["cancel"]          = "Abbrechen",
            ["enter_url"]       = "\u26a0  Bitte URL eingeben",
            ["testing"]         = "\u23f3  Teste\u2026",
            ["tray_active"]     = "Blocking aktiv",
            ["tray_disabled"]   = "Blocking deaktiviert",
            ["tray_noconn"]     = "Keine Verbindung",
            ["tray_connecting"] = "Verbinde\u2026",
            ["menu_enable"]     = "Blocking aktivieren",
            ["menu_disable"]    = "Blocking deaktivieren",
            ["menu_timed"]      = "Zeitlich begrenzt deaktivieren",
            ["menu_5min"]       = "5 Minuten",
            ["menu_10min"]      = "10 Minuten",
            ["menu_30min"]      = "30 Minuten",
            ["menu_1h"]         = "1 Stunde",
            ["menu_2h"]         = "2 Stunden",
            ["menu_5h"]         = "5 Stunden",
            ["menu_dashboard"]  = "Dashboard \u00f6ffnen",
            ["menu_settings"]   = "Einstellungen\u2026",
            ["menu_quit"]       = "Beenden",
            ["connected"]       = "Verbunden",
            ["connected_auth"]  = "Verbunden & authentifiziert!",
            ["no_connection"]   = "Keine Verbindung zu:",
            ["timeout"]         = "Zeit\u00fcberschreitung",
            ["auth_required"]   = "Authentifizierung n\u00f6tig.\nBitte Passwort eingeben.",
            ["login_failed"]    = "Login fehlgeschlagen.\nPasswort pr\u00fcfen.",
            ["conn_failed"]     = "Verbindung fehlgeschlagen.",
        },
        ["es"] = new()
        {
            ["title"]           = "Pi-Hole Tray  \u2014  Ajustes",
            ["connection"]      = "Conexi\u00f3n",
            ["url"]             = "URL",
            ["url_hint"]        = "ej. http://192.168.1.2",
            ["password"]        = "Contrase\u00f1a / API Key",
            ["pw_hint"]         = "v6: Contrase\u00f1a admin  \u2022  v5: API Token",
            ["version"]         = "Versi\u00f3n de Pi-Hole",
            ["v6_label"]        = "v6 (actual)",
            ["v5_label"]        = "v5 (legacy)",
            ["options"]         = "Opciones",
            ["poll_interval"]   = "Intervalo de consulta",
            ["seconds"]         = "segundos",
            ["autostart"]       = "  Iniciar con Windows",
            ["language"]        = "Idioma",
            ["status"]          = "Estado",
            ["ready"]           = "Listo",
            ["test_connection"] = "Probar conexi\u00f3n",
            ["save"]            = "Guardar",
            ["cancel"]          = "Cancelar",
            ["enter_url"]       = "\u26a0  Ingrese la URL",
            ["testing"]         = "\u23f3  Probando\u2026",
            ["tray_active"]     = "Bloqueo activo",
            ["tray_disabled"]   = "Bloqueo desactivado",
            ["tray_noconn"]     = "Sin conexi\u00f3n",
            ["tray_connecting"] = "Conectando\u2026",
            ["menu_enable"]     = "Activar bloqueo",
            ["menu_disable"]    = "Desactivar bloqueo",
            ["menu_timed"]      = "Desactivar temporalmente",
            ["menu_5min"]       = "5 minutos",
            ["menu_10min"]      = "10 minutos",
            ["menu_30min"]      = "30 minutos",
            ["menu_1h"]         = "1 hora",
            ["menu_2h"]         = "2 horas",
            ["menu_5h"]         = "5 horas",
            ["menu_dashboard"]  = "Abrir panel",
            ["menu_settings"]   = "Ajustes\u2026",
            ["menu_quit"]       = "Salir",
            ["connected"]       = "Conectado",
            ["connected_auth"]  = "\u00a1Conectado y autenticado!",
            ["no_connection"]   = "Sin conexi\u00f3n a:",
            ["timeout"]         = "Tiempo agotado",
            ["auth_required"]   = "Se requiere autenticaci\u00f3n.\nIngrese la contrase\u00f1a.",
            ["login_failed"]    = "Inicio de sesi\u00f3n fallido.\nVerifique la contrase\u00f1a.",
            ["conn_failed"]     = "Conexi\u00f3n fallida.",
        },
        ["fr"] = new()
        {
            ["title"]           = "Pi-Hole Tray  \u2014  Param\u00e8tres",
            ["connection"]      = "Connexion",
            ["url"]             = "URL",
            ["url_hint"]        = "ex. http://192.168.1.2",
            ["password"]        = "Mot de passe / Cl\u00e9 API",
            ["pw_hint"]         = "v6 : Mot de passe admin  \u2022  v5 : API Token",
            ["version"]         = "Version de Pi-Hole",
            ["v6_label"]        = "v6 (actuelle)",
            ["v5_label"]        = "v5 (legacy)",
            ["options"]         = "Options",
            ["poll_interval"]   = "Intervalle d'interrogation",
            ["seconds"]         = "secondes",
            ["autostart"]       = "  D\u00e9marrer avec Windows",
            ["language"]        = "Langue",
            ["status"]          = "Statut",
            ["ready"]           = "Pr\u00eat",
            ["test_connection"] = "Tester la connexion",
            ["save"]            = "Enregistrer",
            ["cancel"]          = "Annuler",
            ["enter_url"]       = "\u26a0  Veuillez entrer l'URL",
            ["testing"]         = "\u23f3  Test en cours\u2026",
            ["tray_active"]     = "Blocage actif",
            ["tray_disabled"]   = "Blocage d\u00e9sactiv\u00e9",
            ["tray_noconn"]     = "Pas de connexion",
            ["tray_connecting"] = "Connexion\u2026",
            ["menu_enable"]     = "Activer le blocage",
            ["menu_disable"]    = "D\u00e9sactiver le blocage",
            ["menu_timed"]      = "D\u00e9sactiver temporairement",
            ["menu_5min"]       = "5 minutes",
            ["menu_10min"]      = "10 minutes",
            ["menu_30min"]      = "30 minutes",
            ["menu_1h"]         = "1 heure",
            ["menu_2h"]         = "2 heures",
            ["menu_5h"]         = "5 heures",
            ["menu_dashboard"]  = "Ouvrir le tableau de bord",
            ["menu_settings"]   = "Param\u00e8tres\u2026",
            ["menu_quit"]       = "Quitter",
            ["connected"]       = "Connect\u00e9",
            ["connected_auth"]  = "Connect\u00e9 et authentifi\u00e9 !",
            ["no_connection"]   = "Pas de connexion \u00e0 :",
            ["timeout"]         = "D\u00e9lai d\u00e9pass\u00e9",
            ["auth_required"]   = "Authentification requise.\nVeuillez entrer le mot de passe.",
            ["login_failed"]    = "\u00c9chec de connexion.\nV\u00e9rifiez le mot de passe.",
            ["conn_failed"]     = "\u00c9chec de connexion.",
        },
        ["it"] = new()
        {
            ["title"]           = "Pi-Hole Tray  \u2014  Impostazioni",
            ["connection"]      = "Connessione",
            ["url"]             = "URL",
            ["url_hint"]        = "es. http://192.168.1.2",
            ["password"]        = "Password / Chiave API",
            ["pw_hint"]         = "v6: Password admin  \u2022  v5: API Token",
            ["version"]         = "Versione Pi-Hole",
            ["v6_label"]        = "v6 (attuale)",
            ["v5_label"]        = "v5 (legacy)",
            ["options"]         = "Opzioni",
            ["poll_interval"]   = "Intervallo di polling",
            ["seconds"]         = "secondi",
            ["autostart"]       = "  Avvia con Windows",
            ["language"]        = "Lingua",
            ["status"]          = "Stato",
            ["ready"]           = "Pronto",
            ["test_connection"] = "Testa connessione",
            ["save"]            = "Salva",
            ["cancel"]          = "Annulla",
            ["enter_url"]       = "\u26a0  Inserisci l'URL",
            ["testing"]         = "\u23f3  Test in corso\u2026",
            ["tray_active"]     = "Blocco attivo",
            ["tray_disabled"]   = "Blocco disattivato",
            ["tray_noconn"]     = "Nessuna connessione",
            ["tray_connecting"] = "Connessione\u2026",
            ["menu_enable"]     = "Attiva blocco",
            ["menu_disable"]    = "Disattiva blocco",
            ["menu_timed"]      = "Disattiva temporaneamente",
            ["menu_5min"]       = "5 minuti",
            ["menu_10min"]      = "10 minuti",
            ["menu_30min"]      = "30 minuti",
            ["menu_1h"]         = "1 ora",
            ["menu_2h"]         = "2 ore",
            ["menu_5h"]         = "5 ore",
            ["menu_dashboard"]  = "Apri dashboard",
            ["menu_settings"]   = "Impostazioni\u2026",
            ["menu_quit"]       = "Esci",
            ["connected"]       = "Connesso",
            ["connected_auth"]  = "Connesso e autenticato!",
            ["no_connection"]   = "Nessuna connessione a:",
            ["timeout"]         = "Timeout",
            ["auth_required"]   = "Autenticazione richiesta.\nInserire la password.",
            ["login_failed"]    = "Accesso fallito.\nVerifica la password.",
            ["conn_failed"]     = "Connessione fallita.",
        },
    };

    public static string T(string key, string lang)
    {
        if (All.TryGetValue(lang, out var d) && d.TryGetValue(key, out var v))
            return v;
        if (All["en"].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }

    public static string DetectOsLanguage()
    {
        try
        {
            var code = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
            if (Langs.ContainsKey(code)) return code;
        }
        catch { }
        return "en";
    }

    public static string GetEffectiveLang(string configLang)
    {
        if (!string.IsNullOrEmpty(configLang) && Langs.ContainsKey(configLang))
            return configLang;
        return DetectOsLanguage();
    }
}
